### ISSUE TITLE
Comparison with another "pyAIML"?

### ISSUE THREAD

**Issue by hanfeisun** [cdwfs/pyaiml#2]
I found there is another repo on Github called "pyAIML": https://github.com/creatorrr/pyAIML/

Would it be possible to have some comparison between this pyaiml with that one...

**Comment by mertyildiran** [comment]
@cdwfs is the original author. @hanfeisun checkout https://github.com/creatorrr/pyAIML/issues/2 to learn the current state. Currently, there is no one to maintain this project. Are you willing to maintain it? I'm also willing to maintain it. Maybe we can work together?

**Comment by hanfeisun** [comment]
@mertyildiran That's interesting! I'll give https://github.com/creatorrr/pyAIML/ a try first in my project and see what happens. Also, there is another AIML library which seems being under active development: https://github.com/keiffster/program-y

I'll keep watching these repos for updates...

**Comment by mertyildiran** [comment]
@hanfeisun I wasn't aware of the existence [program-y](https://github.com/keiffster/program-y) thank you for letting me know.

Yeah, that's a good strategy...

**Comment by shubhamivane** [comment]
I am new to AI could you please tell me where should I start.

**Comment by cdwfs** [comment]
The last AI class I took was in college, nearly twenty years ago. Shortly thereafter I got started in computer graphics, and that's where my career has focused since then. I'm not much help with beginner AI materials; sorry! I see some courses on deep learning at Udacity, and I've had good experiences with them in the past.
